### ISSUE TITLE
CONTRIBUTING.md file link broken. 

### ISSUE THREAD

**Issue by CodingSpecies** [The-Cool-Coders/Project-Ideas-And-Resources#24]
At the end of the README.md, where it says to read the CONTRIBUTING.md file, the link is broken as it says `CONTRIBUTING.md` instead of `CONTRIBUTION.md`. Thank you.

**Comment by Subhampreet** [comment]
Hey @CodingSpecies ,

Thanks for raising the issue, actually the CONTRIBUTION.md file isn't also updated, It would be great if you would like to work on that and contribute to this repository and help me in making it big.

Happy Open-Sourcing!!!

**Comment by CodingSpecies** [comment]
@Subhampreet thank you I will work on it.

**Comment by Subhampreet** [comment]
I have assigned you the issue, work on it, and also link it to the PR you send so that the issue gets closed too when I merge your PR.

**Comment by CodingSpecies** [comment]
Sure thanks

**Comment by CodingSpecies** [comment]
#29
